project:
  type: website
  output-dir: docs

website:
  title: "Paweł Czyż"
  site-url: "https://pawel-czyz.github.io/"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: blog.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



