project:
  type: website
  output-dir: docs

website:
  title: "Paweł Czyż"
  site-url: "https://pawel-czyz.github.io/"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: blog.qmd
      - href: publications.qmd
  google-analytics:
    tracking-id: "G-PZ6W6SFE14"
    storage: "none"
    anonymize-ip: true


format:
  html:
    theme: darkly
    css: styles.css
    toc: true



