---
title: "Adjoint group homomorphisms"
description: "Adjoint functors are a core topic in category theory. As group homomorphisms are essentially functors, when do they form an adjunction?"
author: "Paweł Czyż"
date: "6/10/2024"
---

Consider a group $G$.
Its [delooping](https://ncatlab.org/nlab/show/group#delooping) is a one-object category, $\mathbf{B}G$, such that it has a single object $\bullet_G$ and each $g\in G$ is treated as a morphism $\bullet_G \to \bullet_G$.
The morphism composition is then the usual group composition.
A group homomorphism $f\colon G\to H$ is then essentially the same as a functor $\mathbf{B}f\colon \mathbf{B}G\to \mathbf{B}G$ (with the difference that the functor $\mathbf{B}f$ additionally maps the object $\bullet_G$ to the object $\bullet_H$).

Consider now two group homomorphisms, $f\colon G\to H$ and $u\colon H\to G$.
If we treat them as functors, $\mathbf{B}f$ and $\mathbf{B}u$, under which circumstances are they [adjoint](https://en.wikipedia.org/wiki/Adjoint_functors)?
In other words, what are the properties of homomorphisms of $f$ and $u$, such that $\mathbf{B}f \dashv \mathbf{B}u$?

For an adjunction we need a natural isomorphism $\psi_{\bullet_G\bullet_H}\colon \mathrm{Hom}_{\mathbf{B}H}( \mathbf{B}f(\bullet_G), \bullet_H) \to \mathrm{Hom}_{\mathbf{B}G}(\bullet_G, \mathbf{B}g(\bullet_H) )$.This is just a convoluted way of writing that we need a bijection $\psi\colon H\to G$ with additional properties, making it the *natural* isomorphism.

What properties?
Let's introduce some notation. For an arrow $h\in H$ we write $h^\flat = \psi(h)$.
If $\phi\colon G\to H$ be the inverse, $\phi = \psi^{-1}$, and $g\in G$, we write $g^\sharp = \phi(g)$.
Of course, we have $(h^\flat)^\sharp = h$ and $(g^\sharp)^\flat = g$ for all $h$ and $g$.

The first property (naturality in $\mathbf{B}H$) reads that for every $h_1$ and $h_2$ in $H$, we have
$$
    u(h_1) h_2^\flat = (h_1h_2)^\flat,
$$
or equivalently,
$$
  u(h_1) \psi(h_2) = \psi(h_1h_2).  
$$

The second property (naturality in $\mathbf{B}G$) reads that for every $g\in G$ and $h \in H$ it holds that
$$
    (h \circ f(g))^\flat = h^\flat g.
$$

This looks asymmetric, but we can fix it. As $G$ and $H$ have to be bijections, we can write $h = g_1^\sharp$. Rename $g$ to $g_2$. Then,
$$
    (g_1^\sharp f(g_2))^\flat = g_1 g_2,
$$

or equivalently
$$
    g_1^\sharp f(g_2) = (g_1 g_2)^\sharp,
$$

or equivalently
$$
    \phi(g_1) f(g_2) = \phi(g_1g_2).
$$

To summarise, we require
$$
    \phi(g_1)f(g_2) = \phi(g_1 g_2), \quad u(h_1) \psi(h_2) = \psi(h_1 h_2).
$$

for all $g_1, g_2\in G$ and $h_1, h_2 \in H$.
Note that these conditions *differ from* the definition of a homomorphism, having $f(g_2)$ instead of $\phi(g_2)$ and $u(h_1)$ instead of $\psi(h_1)$.
They are also slightly asymmetric, which is related to the fact that adjoint functors also have this asymmetry: we want $f$ to be the left adjoint and $g$ to be the right adjoint. 


These conditions are, actually, very restrictive: if we take $g_1 to be the identity element, then we have
$$
    \phi(1_G) f(g) = \phi(g)
$$

for all $g\in G$.
We can therefore write $f$ as a composition of bijective functions, i.e., $f$ is also bijective.
And as $f$ is a bijective group homomorphism, it *has to be a group isomorphism*.

Analogous argument proves that any right adjoint $u$ has to be a group isomorphism as well.
Let's now think how $f$ and $u$ can be related.
A natural candidate for a right adjoint $u$ for $f$ would be its inverse.

**Proposition:** If $f\colon G\to H$ is a group isomorphism, then we have an adjunction $f \dashv f^{-1}$.

*Proof:* Define $\phi(g) = f(g)$, so that $\psi(h) = f^{-1}(h)$. The naturality equations are then obvious.

If $u$ is a group isomorphism, then also $u^{-1}$ is a group isomorphism, and we obtain $u^{-1} \dashv u$ adjunction.
The above adjunction (i.e., use the inverse) is *almost* the only one existing: [adjoint functors are unique *up to a natural isomorphism*](https://ncatlab.org/nlab/show/adjoint+functor#basic_properties).

Let's therefore think what it means for two group homomorphisms $f_1\colon G\to H$ and $f_2\colon G\to H$ to be naturally isomorphic.
As usual, we have only a single object $\bullet_G$ in the category $\mathbf{B}G$, indexing a single arrow $a\colon \bullet_G \to \bullet_G$, i.e., $a\in G$.
As it is a natural transformation, we have to have
$$
    f_1(g) a = a f_2(g)
$$

for every $g\in G$ and $f_2(g) = a^{-1} f_1(g) a$.
By writing $\sigma_a\colon h\to h$ to be the inner automorphism $h\mapsto a^{-1} h a$, we see that $f_2 = \sigma_a  f_1$ for some $a$. 

This allows us to formulate the theorem characterising adjunctions:

**Theorem:** Every group isomorphism $f\colon G\to H$ has both left and right adjoints, given by $\sigma_{\hat g}  f^{-1}$ for arbitrary elements ${\hat g}\in G$.
Conversely, if $f\dashv u$ is any adjunction, then $f$ and $u$ are group isomorphisms and $u = \sigma_{\hat g} f^{-1}$ for some $\hat g \in G$.

At this point we see that the only examples of adjoint group homomorphisms arise from group isomorphisms and (appropriately conjugated) inverses.

## Where are the monads?

Finally, let's take a look at a monad arising from an adjunction.
Before we start, let's fix some notation.
Take $f \dashv u$ for $u = \sigma_{\hat g} f^{-1}$ and $\hat{g} \in G$.
Hence, we have $uf = \sigma_{\hat g}\colon G\to G$.
The other composition can be obtained as
$$
    fu(h) = f\left( \hat g^{-1} f^{-1}(h) \hat g \right) = f(\hat g)^{-1} h f(\hat g) = \sigma_{\hat h} h
$$

for $\hat h = f(\hat g)$.

We need one more thing: the $\phi = \psi^{-1}$ bijection.
Let's take $\phi(g) = \hat h f(g)$ and $\psi(h) = \hat g^{-1} f^{-1}(h)$.
We have
$$
    \psi( \phi(g) ) = \hat g^{-1} f^{-1} ( \hat h f(g) ) = \hat g^{-1} f^{-1}(\hat h) g = \hat g^{-1} \hat g g = g
$$

and

$$
    \phi( \psi(h) ) = \hat h f( \hat g^{-1} f^{-1}(h) ) = \hat h f(\hat g)^{-1} h = h,
$$

so that these are indeed inverse to each other.
We can also verify that

$$
    \phi(g_1)f(g_2) = \hat h f(g_1)f(g_2) = \hat h f(g_1 g_2) = \phi(g_1 g_2) 
$$
and
$$
    u(h_1) \psi(h_2) = \left(\hat g^{-1} f^{-1}(h_1) \hat g\right) \left( \hat g^{-1} f^{-1}(h_2) \right) = \hat g^{-1} f^{-1}(h_1h_2) = \psi(h_1 h_2). 
$$

The unit of the adjunction is given by
$$
    \eta = (1_H)^{\flat} = \psi(1_H) = \hat g^{-1}
$$

and is a natural transformation from the identity functor
$1_{\mathbf{B}G}$ to the functor given by $uf = \sigma_{\hat g}$, which can be verified as
$$
    \hat g^{-1} (-) =  \left( \hat g^{-1} ( - ) \hat g\right) \hat g^{-1}.
$$

What is the counit? Analogously, it is $\epsilon = (1_G)^\sharp = \hat h$.
Let's quickly verify the triangle identities:

$\epsilon f(\eta) = \hat h f( \hat g^{-1} ) = 1_H$
and
$u(\epsilon) \eta = (\hat g^{-1} f^{-1}(\epsilon) \hat g) \hat g^{-1} = \hat g^{-1} f^{-1}(\hat h) = 1_G$.

The monad now is given by a functor $t = uf = \sigma_{\hat g}\colon G\to G$, the unit $\eta = \hat g^{-1}$, and the multiplication $\mu = u\epsilon f$, which is a natural transformation from $t^2$ to $t$.
More explicitly, multiplication is given by $\mu = u(\epsilon) = \sigma_{\hat g}f^{-1}(\epsilon) = \sigma_{\hat g}( \hat g ) = \hat g$.
It is a natural transformation as
$$
    \mu \, t^2(g) = t(g)\, \mu  
$$

for every $g\in G$: both sides evaluate to $\hat g^{-1}\, g\, \hat g^2$.

If $\hat g$ is taken to be the identity element, then this monad is just the identity monad.
What is the meaning of this one? I am not sure...
