---
title: "Proofs that pi and e are irrational"
description: "Two short and well-known proofs of irrationality."
author: "Paweł Czyż"
date: "4/2/2024"
execute:
  freeze: auto
---

Timothy Chow wrote a great paper [*A well-motivated proof that pi is irrational*](https://arxiv.org/abs/2403.20140), where he explains a proof of irrationality of $e$ (attributed to Fourier) and a proof of irrationality of $\pi$, which originally appeared in the I. Niven's brilliant one-page article.

In this post I'll just recall both proofs, so I can remember them: original articles will be more informative.

## Irrationality of $e$

Suppose that $e=a/b$ for positive integers $a$ and $b$. We can write
$$
e = \sum_{n=0}^{\infty} \frac{1}{n!}
$$

and reach a contradiction by studying an *integer*:

$$
0 < b!\cdot e - b!\sum_{n=0}^b \frac{1}{n!} = \sum_{k=1}^{\infty} \frac{b!}{(b+k)!} < \sum_{k=1}^{\infty} \frac{1}{(b+1)^k} = \frac{1}{b} \le 1.
$$

Hence, this integer would lie strictly between $0$ and $1$, what is impossible.

More generally, T. Chow shows that a similar argument applies to prove irrationality for $e^r$, where $r$ is a positive integer. From there, it's easy to show that 

## Irrationality of $\pi$

Suppose that $\pi=a/b$ for positive integers $a$ and $b$. Let $n$ be be a positive integer and define
$$
f(x)=\frac{x^n(a-bx)^n}{n!}
$$

The main idea of I. Niven's proof is to show that the definite integral
$$
I := \int \limits_0^\pi f(x) \sin x\, \mathrm{d}x
$$

is an integer. But for $0 < x < \pi$ there are bounds
$$
0 < f(x) \sin x < \frac{\pi^n\cdot (a-0)^n}{n!} = \frac{ (\pi a)^n }{n!},
$$

so that for sufficiently large $n$ we have $0 < I < 1$. 

Hence, the whole difficulty lies in proving that $I \in \mathbb Z$.

Define
$$
F(x) = f(x) - f''(x) + f^{(4)}(x) - \cdots + (-1)^n f^{(2n)}(x),
$$

where $f^{(k)}$ is the $k$-th derivative of $f$.
We have

$$\begin{align*}
\frac{\mathrm{d}}{\mathrm{d} x}\left( F'(x) \sin x - F(x) \cos x \right) &= F''(x) \sin x + F'(x) \cos x - F'(x) \cos x + F(x) \sin x\\
&= (F(x) + F''(x)) \sin x = f(x) \sin x,
\end{align*}$$
so that
$$
\int\limits_0^\pi f(x) \sin x\, \mathrm{d}x = \big[F'(x) \sin x - F(x) \cos x\big]_0^\pi = F(0) + F(\pi).
$$

We can prove that $F(0) + F(\pi)$ is an integer by proving that all derivatives $f^{(k)}_n(0)$ and $f^{(k)}_n(\pi)$ are integers. 

First, note that $f_n(x) = f_n(a/b - x) = f_n(\pi - x)$, so that $f^{(k)}_n(0) = \pm f^{(k)}_n(\pi)$.
To prove that $f^{(k)}_n(0)$ is an integer, observe that each summand in $f_n$ has a form $u x^{n+r} / n!$, where $u$ is an integer and $r \ge 0$. If we differentiate it $k$ times and evaluate it at $x=0$ we will either have $0$ (for $k \neq n+r$) or $u \cdot (n+r)! / n!$ for $k=n+r$, which is an integer.

## Links

- I. Niven, [*A simple proof that $\pi$ is irrational*](https://projecteuclid.org/journals/bulletin-of-the-american-mathematical-society-new-series/volume-53/issue-6/A-simple-proof-that-pi-is-irrational/bams/1183510788.full), 1947: a one-page proof that $\pi$ is irrational.
- Kostya_I, [Exposition of Niven's proof](https://mathoverflow.net/questions/444082/to-prove-irrationality-why-integrate/444167#444167), 2023: a short note connecting Niven's proof to orthogonal polynomials.
- T. Chow, [*A well-motivated proof that pi is irrational*](https://arxiv.org/abs/2403.20140), 2024: proof of irrationality of $\pi$ and $e^r$ for nonzero rational $r$.

## Appendix: some theorems of transcendental number theory

I often forget the names of major results of transcendental number theory. Let's quickly recall them:

**[Lindemann–Weierstrass theorem](https://en.wikipedia.org/wiki/Lindemann%E2%80%93Weierstrass_theorem)**: if $\alpha_1, \dotsc, \alpha_n$ are algebraic numbers linearly independent over $\mathbb Q$, then $e^{\alpha_1}, \dotsc, e^{\alpha_n}$ are [algebraically independent](https://en.wikipedia.org/wiki/Algebraic_independence) over $\mathbb Q$.

**[Gelfond–Schneider theorem](https://en.wikipedia.org/wiki/Gelfond%E2%80%93Schneider_theorem)**: let $a \in \mathbb C\setminus \{0, 1\}$ be a complex algebraic number. If $b \in \mathbb C\setminus (\mathbb Q\times \{0\})$ is an irrational complex algebraic number, then $a^b = \exp(b\log a)$ is transendental (independently on the branches of the functions used).