---
title: "On the properties and estimation of pointwise mutual information profiles"
type: "article"
author: "P. Czyż, F. Grabowski, J.E. Vogt, N. Beerenwinkel, A. Marx"
year: "2023"
venue: "Preprint, submitted"
preprint: "https://arxiv.org/abs/2310.10240"
code: "https://github.com/cbg-ethz/bmi"
toc: true
---



## Abstract
The pointwise mutual information profile, or simply profile, is the distribution of pointwise mutual information for a given pair of random variables.
One of its important properties is that its expected value is precisely the mutual information between these random variables.
In this paper, we analytically describe the profiles of multivariate normal distributions and introduce a novel family of distributions, Bend and Mix Models, for which the profile can be accurately estimated using Monte Carlo methods.
We then show how Bend and Mix Models can be used to study the limitations of existing mutual information estimators, investigate the behavior of neural critics used in variational estimators, and understand the effect of experimental outliers on mutual information estimation.
Finally, we show how Bend and Mix Models can be used to obtain model-based Bayesian estimates of mutual information, suitable for problems with available domain expertise in which uncertainty quantification is necessary.


## Links

- This is a direct follow-up to the [*Beyond normal*](beyond-normal.qmd) manuscript.

## Citation
```
@misc{pmi-profiles,
      title={On the Properties and Estimation of Pointwise Mutual Information Profiles}, 
      author={Paweł Czyż and Frederic Grabowski and Julia E. Vogt and Niko Beerenwinkel and Alexander Marx},
      year={2023},
      eprint={2310.10240},
      archivePrefix={arXiv},
      primaryClass={stat.ML}
}
```

## Behind the scenes

- The full story has been described on the [blog](../posts/on-beyond-normal.qmd).
- The first version of this manuscript was titled *The mixtures and the critics: on the pointwise mutual information profiles of fine distributions*. This is, of course, named after J.R.R. Tolkien's [*The monsters and the critics*](https://en.wikipedia.org/wiki/Beowulf:_The_Monsters_and_the_Critics). I was very stubborn on keeping this, but after weeks of discussions I was eventually convinced that the new title is informative about the content.

